// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd8Wvkq7e_utBsntyAtJsOubXlb7DaWNg',
    appId: '1:1056043770352:web:df991af1d56aae1c197d35',
    messagingSenderId: '1056043770352',
    projectId: 'goo-gg-dev',
    authDomain: 'goo-gg-dev.firebaseapp.com',
    storageBucket: 'goo-gg-dev.appspot.com',
    measurementId: 'G-HTCR9HV83Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu2wJXbut8ky3g6CZnARCz6UTXEsyM6PI',
    appId: '1:1056043770352:android:160c75b884a0380a197d35',
    messagingSenderId: '1056043770352',
    projectId: 'goo-gg-dev',
    storageBucket: 'goo-gg-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrOFaxgDylzq8tw3kIzoKwRVFofIMaY5I',
    appId: '1:1056043770352:ios:3fa9f2edf67c7fec197d35',
    messagingSenderId: '1056043770352',
    projectId: 'goo-gg-dev',
    storageBucket: 'goo-gg-dev.appspot.com',
    iosBundleId: 'com.goo.gooGgApplication',
  );
}
